### ISSUE TITLE
"fixed" option?

### ISSUE THREAD

**Issue by bjodah** [WestHealth/pyvis#17]
I'm trying to set positions manually by giving x, y and sett physics=False but can't get it to work.
The documentation mentions a "fixed" option:
https://github.com/WestHealth/pyvis/blob/5b7393d3c4fff561f1443ad45072ba3787a9a0be/pyvis/network.py#L168

But I can't seem to find any other mention of it when grep'ing the source...

**Comment by boludo00** [comment]
hey @bjodah,
hmmm, this is odd, since I just tested from the following documentation example
https://pyvis.readthedocs.io/en/latest/tutorial.html#adding-list-of-nodes-with-properties

Can I see what you're doing to get this behavior?

**Comment by boludo00** [comment]
My guess would be if you're passing in

**Comment by dmontaner** [comment]
First of all thanks for the package!!! Is a great tool!!!

In case it helps for this issue...

@boludo00. In the web example there are not edges in the graph. This means the "physics" do not move the nodes after the graph is initialized and thus, the nodes stay in the assigned x,y coordinates.

But, if you add some edges to the graph, the "physics" will modify the original locations of the nodes given in the x,y coordinates.

This is because in the web example the "physics" parameter is not set and the default value (True) applies.

The function `pyvis.network.Network.add_nodes` does not allow you to set the "physics" parameter and may be this causes some confusion.

@bjodah. You can set the "physics" parameter in the `g.nodes` list. See my example below. You could also use the function `pyvis.network.Network.add_node` (without the final s) which lets you set the "physics" value to `False` for each included node.

This modification of the web example shows how adding edges changes the x,y node values... and how adding the "physics" keeps then the given coordinates:

I am using `pyvis.__version__`:  "0.1.7.0".

```
from pyvis.network import Network

g = Network()
g.add_nodes([1, 2, 3],
            value=[1, 1, 1],
            title=["I am node 1", "node 2 here", "and im node 3"],
            x=[0, 100, 100],
            y=[0, 100, 200], label=["NODE 1", "NODE 2", "NODE 3"],
            color=["#00ff1e", "#162347", "#dd4b39"])

g.show('just_nodes.html')

g.add_edge(1, 2)
g.add_edge(1, 3)

g.show('with_edges.html')

for n in g.nodes:
    n.update({'physics': False})

g.show('with_edges_and_physics.html')
```

**Comment by boludo00** [comment]
![image](https://user-images.githubusercontent.com/8398241/65172089-3cb79f00-da01-11e9-8a29-89bbf8a982ed.png)

What I have done here is use networkx to generate a layout (dict of node id mappings to array of x and y). Then iterate through nodes and update each node object with relevant 'x' and 'y' attributes from the returned layout. You'll notice I also scaled the coordinates up by a factor of 1000 since resulting visual included nodes sitting on top of each other since the original coordinates were too small for the canvas. Also disable physics like in the example to make sure your layout is static.

You could also include the x and y coordinates when you add a node with `add_node` or `add_nodes` like in the example on the docs: https://pyvis.readthedocs.io/en/latest/tutorial.html#adding-list-of-nodes-with-properties

**Comment by stefanzero** [comment]
In the source code listed in the documentation [generate_html](https://pyvis.readthedocs.io/en/latest/_modules/pyvis/network.html), it shows that the option **physics** has a sub-key **enabled**.

In the Network constructor, add this dictionary to **physics**:

    Network(options={"physics": {"enabled": False}})
