### ISSUE TITLE
Loading Bar Stuck on 0% when Background has rendered

### ISSUE THREAD

**Issue by DarylGraves** [WestHealth/pyvis#25]
If your node graph is very large the loading bar will remain visible (at 0%) even though the graph has loaded in the background. If you customise the graph with the menu you can see the graph changing in the background and ultimately you have to push F12 in the browser and delete the HTML element for the loading bar to see the final result.

**Comment by boludo00** [comment]
How many nodes are you loading? I've just tested with python3.7 and 500 nodes with no problem. Could you share a snippet so I could reproduce?
Just need to see if it's a problem stemming from the python layer or the underlying javascript.

**Comment by DarylGraves** [comment]
More than 1,000 nodes - but there's approximately 400 "root" nodes with up to 4 things attached to them.

The nodes are all there and joined as expected, if you delete the HTML element you can then navigate the graph as normal.

Another question whilst I have you - Is there a way to configure the template so it always defaults to a certain structure? I want a hierarchical structure but it always defaults back to the default when my code is ran. I've changed the .html manually in the template but it never seems to save.

Thanks!

**Comment by boludo00** [comment]
I've generated a random tree with n=1000 using hierarchical layout with below results. So I am not sure what could be causing that behavior. I am using chrome as well and pyvis version 0.1.5.1. Have you noticed this behavior on other graphs that display a loading bar? By default the loading bar will displayfor graphs with more than 100 nodes. 

![1000](https://user-images.githubusercontent.com/8398241/54147016-7a9e8f80-43ee-11e9-901e-0f664284bca2.gif)

As far as the hierarchical layout goes, that option is currently not configurable from the python layer although the capabilities are there. A separate issue could be created to implement this however since it is not convenient to run code the generate the initial graph and then modify the html manually to get your results.

**Comment by DarylGraves** [comment]
Thanks, I get the same issue in Internet Explorer too and on a few of the graphs I've generated. I definitely think it's size related - I think maybe I'm underestimating when I say 1,000.

![example](https://user-images.githubusercontent.com/46203429/54148983-2a92ed80-442d-11e9-8646-f06da0db4929.gif)

Unfortunately for me personally, it doesn't really matter anymore but I wanted to make you aware. In my example though my script was designed to parse a SQL table every hour and create a ready-to-go graph which we could link to on our work intranet. I hadn't anticipated that I couldn't alter the layout without manually editing the HTML so shelving my project.

**Comment by boludo00** [comment]
Oh I see you are using the configuration overlay as well. Have you tried without that option? Thanks for bringing it to my attention though. It could very well be that the CSS is not playing nicely with each other. I will still look into this, in the meantime I will open a ticket for adding layout support.

**Comment by boludo00** [comment]
Im going to leave this open until the other matter is squashed, but the dynamic hierarchical tweaking is in place due to the latest PR. Thanks for the feedback! Good to see that features are being requested.

**Comment by DarylGraves** [comment]
No problem! I just wish I was at a level where I could help do the requests instead of ask you to do them! :)

**Comment by benbini** [comment]
having the same issue, *only when physics is not enabled*.  I believe this issue is due to the following logic in template.html:

```
{% if nodes|length > 100 %}
```

You need to check first that physics is enabled, otherwise stabilization will never be achieved or progress, because there is no physics and therefore no stabilization.

**Comment by dipanshuhaldar** [comment]
Well I am working with a graph that is a directed graph with 
Number of nodes: **61392**
Number of edges: **97433**

When I try to visualise this on AWS Sagemaker, even on a 64 gigs instance, all I get is a blank HTML window
