### ISSUE TITLE
Network.from_nx doesn't inherit all properties

### ISSUE THREAD

**Issue by nanodan** [WestHealth/pyvis#45]
It seems like Network.from_nx doesn't inherit all properties of the graph, only the nodes and edges. Any color, and other properties have to be re-created/added to the Network representation of the networkx graph.

**Comment by boludo00** [comment]
Yes you are correct in noticing that. Currently there is no way to preserve the properties coming in from networkx. My reasoning for this was that Networkx allows you to provide any property to the nodes while in pyvis the proeprties need to be structured specifically in order to be captured in the visualizaiton. So if a property provided does not exist in the pyvis layer it would not be reflected in the final output. I would like to eventually implement a more general way to capture anything created through networkx though.
