### ISSUE TITLE
Displaying very large networks

### ISSUE THREAD

**Issue by g-ioannou** [WestHealth/pyvis#84]
Hello,

I'm trying to render and display very large networks(1.000.000+ nodes, 12.000.000+ edges) which obviously either crashes my browser or takes ages to load.

Do you have any tips to achieve this visualization?

**Comment by laimaretto** [comment]
hello @g-ioannou ; I've never tried such large networks with pyvis ... but, may be, you should try another in the meanwhile, such a [gephi](https://gephi.org/)...

**Comment by boludo00** [comment]
I don't actually know the physical limitations of VisJS when it comes to networks of that size. I know tweaking with the physics algorithms can help, as well as calculating the node positions beforehand and manually supplying them on network creation...
I hope a visJS dev can chime in on this though since that is obviously a huge problem.
